live_config_reload = true

[cursor]
vi_mode_style = "Block"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
  { key = "Space", mods = "Shift",                      action = "ToggleViMode" },
  { key = "I",     mods = "Shift", mode = "Vi|~Search", action = "First" },
  { key = "A",     mods = "Shift", mode = "Vi|~Search", action = "Last" }
]
